### ISSUE TITLE
Can not find where the log file is saved.

### ISSUE THREAD

**Issue by sameerraja93** [TheLazyTomcat/TelemetryLog#1]
Hi,

Im using the dll file in the plugin folder and I do get a sdk warning when I run the game which means it is running but I can not see the saved log file anywhere.

**Comment by TheLazyTomcat** [comment]
The code is very old, and it was one-off project, so I do not remember it too well and I cannot test it, but looking into SimpleLog library, it seems the file might be in the folder where the loading executable (ie. the game's main EXE) is located.

**Comment by TheLazyTomcat** [comment]
Sorry, looked at it again, and given this line:
`fLog.StreamFileName := ExtractFilePath(GetModuleName(hInstance)) + 'telemetry.log';`
... the file should be in the folder with the library (DLL).

**Comment by TheLazyTomcat** [comment]
Since there is no response for three days and because I will go offline for several weeks again, I am marking this as invalid and closing.
